### ISSUE TITLE
input() called at a global level breaks pytest

### ISSUE THREAD

**Issue by cclauss** [Lablnet/Web-Spider#2]
Calling the __input()__ function at a global level will break __pytest__:
https://github.com/Lablnet/Web-Spider/blob/master/src/main.py#L14

Can we move that line inside __main()__ ?

**Comment by lablnet** [comment]
> Calling the **input()** function at a global level will break **pytest**:
> https://github.com/Lablnet/Web-Spider/blob/master/src/main.py#L14
> 
> Can we move that line inside **main()** ?

yes it can be but am thinking to make it more easy to use, instead we touch file from /src, everything can easily done in index.py file 
just like in todo 
`Make Package flexible and easy to use without touching core file`
